-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 14:53:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_app` DEFAULT CHARACTER SET utf8 ;
USE `todo_app` ;

-- -----------------------------------------------------
-- Table `todo_app`.`priorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`priorities` (
  `id_p` INT NOT NULL,
  `priority_task` VARCHAR(15) NOT NULL COMMENT 'in this part theres gonna be the priorities tasks.',
  PRIMARY KEY (`id_p`),
  UNIQUE INDEX `Ninguna_UNIQUE` (`id_p` ASC),
  UNIQUE INDEX `Baja_UNIQUE` (`priority_task` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_app`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(25) NOT NULL,
  `description` LONGTEXT NULL,
  `end_date` DATE NOT NULL,
  `start_date` DATE NOT NULL,
  `created_time` TIME NOT NULL,
  `is_complete` TINYINT(0) NULL,
  `priority_priority_id` INT NOT NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE INDEX `Id_tarea_UNIQUE` (`task_id` ASC),
  INDEX `fk_task_priority1_idx` (`priority_priority_id` ASC),
  CONSTRAINT `fk_task_priority1`
    FOREIGN KEY (`priority_priority_id`)
    REFERENCES `todo_app`.`priorities` (`id_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `confirm_password` VARCHAR(60) NOT NULL,
  `created` DATE NOT NULL,
  `task_task_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_users_task_idx` (`task_task_id` ASC),
  CONSTRAINT `fk_users_task`
    FOREIGN KEY (`task_task_id`)
    REFERENCES `todo_app`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
prioritiesprioritiestasktasktodo_apptodo_apptodo_apptodo_app